name: impnode-gpu
channels:
  - conda-forge
  - pyg
  - nvidia
  # We want to have a reproducible setup, so we don't want default channels,
  # which may be different for different users. All required channels should
  # be listed explicitly here.
  - nodefaults

# when new dependencies are added use `conda env update`
dependencies:
  - python=3.10.*  # or don't specify the version and use the latest stable Python
  - pip  # pip must be mentioned explicitly, or conda-lock will fail
  - conda-forge::glpk=5.0
  - nvidia:cudatoolkit=11.3
  - pytorch::pytorch=1.*
  - pyg:pytorch-scatter
  - poetry=1.*